#Epic: SPD-161
#Story: SPD-165
@regression @nightly @SPD-161 @SPD-165
Feature: Create Account - Schema Validation

  @SPD-161_SPD-165_Precondition
  Scenario: PreCondition - Create required Entities, Actors & Roles
    Given the following "Feature" level precondition "inte904" are generated and published via adapter "ASXML"
      | PreconditionKey | EntityName                          | LEI                             | BAH_BizMsgIdr                       | MessageId                           | CreationDateTime                     | PartyIdValidFrom | OpeningDate | PartyNameValidFrom | PartyType |
      | Entity1         | CBA MARKETS LTD-${EXEC_UID}         | #{ADD_NODE}549300FBHFW3O5LH5M59 | ${BizMsgIdr::format=00002\|Entity1} | ${MessageId::format=00002\|Entity1} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}             | ${T}        | ${T}               | ENTY      |
      | Entity2         | COMMONWEALTH SECURITIES-${EXEC_UID} | #{ADD_NODE}549300FBHFW3O5LH5M69 | ${BizMsgIdr::format=00002\|Entity2} | ${MessageId::format=00002\|Entity2} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}             | ${T}        | ${T}               | ENTY      |
    And read the number of outgoing messages "2" on queue "ASXML_OUT" for message type "inte905" and store in scenario context
    And the following precondition table are persisted to "Feature" properties file
      | PreconditionKey | EntityId                        |
      | Entity1         | ${EntityId::key=00002\|Entity1} |
      | Entity2         | ${EntityId::key=00002\|Entity2} |
    And the following "Feature" level precondition "inte904" are generated and published via adapter "ASXML"
      | PreconditionKey | BAH_BizMsgIdr                          | MessageId                              | CreationDateTime                     | PartyIdValidFrom | PartyType | ActorId                    | OpeningDate | MessagePartyId_BIC                            | MessagePartyId_UIC | PartyNameValidFrom | MessagePartyIdType | EntityId                                | Designation                   |
      | Actor_CDRA      | ${BizMsgIdr::format=00002\|Actor_CDRA} | ${MessageId::format=00002\|Actor_CDRA} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}             | ACTR      | ${ActorId::format=ActorId} | ${T}        | #{ADD_NODE}${MessagePartyId_BIC::format=BIC8} | #{REMOVE_NODE}     | ${T}               | BIC8               | #{ADD_NODE}${#FEATURE#Entity1.EntityId} | #{ADD_NODE}LOAN A/C           |
      | Actor_CSPA      | ${BizMsgIdr::format=00002\|Actor_CSPA} | ${MessageId::format=00002\|Actor_CSPA} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}             | ACTR      | ${ActorId::format=ActorId} | ${T}        | #{ADD_NODE}${MessagePartyId_BIC::format=BIC8} | #{REMOVE_NODE}     | ${T}               | BIC8               | #{ADD_NODE}${#FEATURE#Entity2.EntityId} | #{ADD_NODE}MARGIN  A/C        |
      | Actor_CETA      | ${BizMsgIdr::format=00002\|Actor_CETA} | ${MessageId::format=00002\|Actor_CETA} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}             | ACTR      | ${ActorId::format=ActorId} | ${T}        | #{ADD_NODE}${MessagePartyId_BIC::format=BIC8} | #{REMOVE_NODE}     | ${T}               | BIC8               | #{ADD_NODE}${#FEATURE#Entity2.EntityId} | #{ADD_NODE}MARGIN LENDING A/C |
    And Verify the number of outgoing messages on outbound adapter "ASXML_OUT" recieved are "3"
    And the following "Feature" level precondition "inte904" are generated and published via adapter "ASXML"
      | PreconditionKey | BAH_BizMsgIdr                         | MessageId                             | CreationDateTime                     | PartyIdValidFrom | PartyType | ActorId                        | OpeningDate | RoleType        | PartyNameValidFrom | PermissionType1 | PermissionType2 |
      | ACCR_CDRA       | ${BizMsgIdr::format=00002\|ACCR_CDRA} | ${MessageId::format=00002\|ACCR_CDRA} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}             | ROLE      | ${#FEATURE#Actor_CDRA.ActorId} | ${T}        | #{ADD_NODE}ACCR | ${T}               | #{ADD_NODE}CDRA | #{NO_ACTION}    |
      | ACCR_CSPA       | ${BizMsgIdr::format=00002\|ACCR_CSPA} | ${MessageId::format=00002\|ACCR_CSPA} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}             | ROLE      | ${#FEATURE#Actor_CSPA.ActorId} | ${T}        | #{ADD_NODE}ACCR | ${T}               | #{ADD_NODE}CSPA | #{NO_ACTION}    |
      | ACCR_CETA       | ${BizMsgIdr::format=00002\|ACCR_CETA} | ${MessageId::format=00002\|ACCR_CETA} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}             | ROLE      | ${#FEATURE#Actor_CETA.ActorId} | ${T}        | #{ADD_NODE}ACCR | ${T}               | #{ADD_NODE}CETA | #{NO_ACTION}    |
    And Verify the number of outgoing messages on outbound adapter "ASXML_OUT" recieved are "3"

  ##########################################################################################################################
  #PAC1 : Schema Validation
  #########################################################################################################################
  #PAC3 : Technical Nacks & Business Nacks
  #########################################################################################################################
  #PAC8 : Validating Mandatory Message Elements
  #########################################################################################################################
  Scenario Outline: PAC1 PAC3 PAC8 Account Creation message - Schema invalid - <Description>
    When I generate a message from template for "acct001" using datatable and publish on adapter "ISO"
      | BAH_From  | BAH_BizMsgIdr                               | MessageId   | BAH_CreDt                 | SctiesAcct_Id   | SctiesAcct_RltdPtyId   | SctiesAcct_RspnsblPtyId   | SctiesAcct_OpngDt   | SctiesAcct_Type   | SctiesAcct_HoldInd   | SctiesAcct_NegPos   | SctiesAcct_EndInvstrFlg   | SctiesAcct_PricgSchme   | Sup_AcctType   | Sup_Name   | Sup_AdrLine1              | Sup_TwnNm              | Sup_CtrySubDvsn | Sup_Ctry      | Sup_ResInd              | Sup_ComMtdCd   |
      | <ActorId> | <ActorId>${BAH_BizMsgIdr::format=\|Account} | <MessageId> | ${T::DateFormatter=ZuluWithMilliSec} | <SctiesAcct_Id> | <SctiesAcct_RltdPtyId> | <SctiesAcct_RspnsblPtyId> | <SctiesAcct_OpngDt> | <SctiesAcct_Type> | <SctiesAcct_HoldInd> | <SctiesAcct_NegPos> | <SctiesAcct_EndInvstrFlg> | <SctiesAcct_PricgSchme> | <Sup_AcctType> | <Sup_Name> | #{ADD_NODE}<Sup_AdrLine1> | #{ADD_NODE}<Sup_TwnNm> | #{ADD_NODE}NSW  | #{ADD_NODE}AU | #{ADD_NODE}<Sup_ResInd> | <Sup_ComMtdCd> |
    Then verify NACK with number of messages "1" on outbound queue of "ASXML_OUT" and on poison queue of inbound adapter "ASXML" with message type "comm807"
      | Validate_BAH | Validate_Rltd_BAH         | BAH_To    | Nack_Rltd_RefId                             | RejectReasonCode | RejectReasonDescription   |
      | true         | true::IngressLink=acct001 | <ActorId> | <ActorId>${OriginalMsgId::format=\|Account} |             0099 | <RejectReasonDescription> |
    And Verify the "Account" report doesn't exist in ODS for the following attributes from the below table
      | ActorId   | AccountType    | ResidencyIndicator |
      | <ActorId> | <Sup_AcctType> | <Sup_ResInd>       |

    #Mandatory fields in Account Creation Request block missing
    @REPORT_SPD-161_SPD-165_1
    Examples: 
      | Description                                                         | ActorId                        | MessageId                               | SctiesAcct_Id  | SctiesAcct_RltdPtyId | SctiesAcct_RspnsblPtyId | SctiesAcct_OpngDt | SctiesAcct_Type | SctiesAcct_HoldInd | SctiesAcct_NegPos | SctiesAcct_EndInvstrFlg | SctiesAcct_PricgSchme | Sup_AcctType | Sup_Name             | Sup_AdrLine1             | Sup_TwnNm  | Sup_ResInd | Sup_ComMtdCd    | RejectReasonDescription                                                                          |
      | Account - Transaction Id is blank                                   | ${#FEATURE#Actor_CDRA.ActorId} |                                         | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | RICHARD PTY LTD      | 3/250 CARRINGTON ROAD    | COOGEE     | MIXD       |                 | Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'Max35Text' |
      | Payload without Account - Transaction Id element                    | ${#FEATURE#Actor_CDRA.ActorId} | #{REMOVE_NODE}                          | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | William PTY LTD      | 3/240 CARRINGTON ROAD    | COOGEE     | DMST       |                 | Id}' is expected                                                                                 |
      | Account - Id is blank                                               | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} |                | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | William PTY LTD      | 3/240 CARRINGTON ROAD    | COOGEE     | DMST       |                 | Value '' is not facet-valid with respect to pattern 'NONREF'                                     |
      | Payload without Account - Id element                                | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{REMOVE_NODE} | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | William PTY LTD      | 3/240 CARRINGTON ROAD    | COOGEE     | DMST       |                 | Id}' is expected                                                                                 |
      | Account - Related Party Identification is blank                     | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   |                      | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | RICHARD PTY LTD      | 3/250 CARRINGTON ROAD    | COOGEE     | MIXD       |                 | Value '' is not facet-valid with respect to enumeration '[XASXAU2S]'                             |
      | Payload without Account - Related Party Identification element      | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{REMOVE_NODE}       | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | William PTY LTD      | 3/240 CARRINGTON ROAD    | COOGEE     | DMST       |                 | RltdPtyId}' is expected                                                                          |
      | Account -  Responsible Party Identification is blank                | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         |                         | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | RICHARD PTY LTD      | 3/250 CARRINGTON ROAD    | COOGEE     | MIXD       |                 | Value '' is not facet-valid with respect to enumeration '[XASXAU2S]'                             |
      | Payload without Account -  Responsible Party Identification element | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{REMOVE_NODE}          | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | William PTY LTD      | 3/240 CARRINGTON ROAD    | COOGEE     | DMST       |                 | RspnsblPtyId}' is expected                                                                       |
      | Account - Opening Date is blank                                     | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            |                   | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SPSD         | Schneider PTY LTD    | 101 HARRINGTON ROAD      | Boral      | DMST       | #{ADD_NODE}POST | '' is not a valid value for 'date'                                                               |
      | Payload without Account - Opening Date element                      | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | #{REMOVE_NODE}    | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SPSD         | P&J PTY LTD          | 98 HARRINGTON ROAD       | Boral      | FRGN       | #{ADD_NODE}POST | OpngDt}' is expected                                                                             |
      | Account - Type is blank                                             | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              |                 | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SPSD         | Schneider PTY LTD    | 101 HARRINGTON ROAD      | Boral      | DMST       | #{ADD_NODE}POST | Value '' is not facet-valid with respect to enumeration '[CSDP]'                                 |
      | Payload without Account - Type element                              | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | #{REMOVE_NODE}  | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SPSD         | P&J PTY LTD          | 98 HARRINGTON ROAD       | Boral      | FRGN       | #{ADD_NODE}POST | Tp}' is expected                                                                                 |
      | Hold Indicator is blank                                             | ${#FEATURE#Actor_CETA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            |                    | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SETT         | Energy Australia LTD | 56 GREAT WESTREN HIGHWAY | Cooma      | FRGN       |                 | Value '' is not facet-valid with respect to enumeration '[false]'                                |
      | Payload without Account - Hold Indicator element                    | ${#FEATURE#Actor_CETA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{REMOVE_NODE}     | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SETT         | RICHARD PTY LTD      | 70 GREAT WESTREN HIGHWAY | Cooma      | DMST       |                 | HldInd}' is expected                                                                             |
      | Negative Position is blank                                          | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       |                   | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | RJ  PTY LTD          | 3/240 CARRINGTON ROAD    | Penrith    | FRGN       |                 | Value '' is not facet-valid with respect to enumeration '[false]'                                |
      | Payload without Account - Negative Position element                 | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{REMOVE_NODE}    | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | LJHooker Pty LTD     | 3/240 CARRINGTON ROAD    | Penrith    | MIXD       |                 | NegPos}' is expected                                                                             |
      | End Investor Flag is blank                                          | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      |                         | #{NO_ACTION}          | SPSD         | RICHARD PTY LTD      | 3/240 CARRINGTON ROAD    | Richmond   | DMST       | #{ADD_NODE}POST | Value '' is not facet-valid with respect to enumeration '[NORE]'                                 |
      | Payload without Account - End Investor Flag element                 | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{REMOVE_NODE}          | #{NO_ACTION}          | SPSD         | RICHARDSON PTY LTD   | 3/240 CARRINGTON ROAD    | Richmond   | FRGN       | #{ADD_NODE}POST | EndInvstrFlg}' is expected                                                                       |
      | Pricing Scheme is blank                                             | ${#FEATURE#Actor_CETA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            |                       | ACCU         | P&J  PTY LTD         | 3/240 CARRINGTON ROAD    | Leppington | DMST       |                 | Value '' is not facet-valid with respect to enumeration '[NORE]'                                 |
      | Payload without Account - Pricing Scheme element                    | ${#FEATURE#Actor_CETA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}   | #{NO_ACTION}         | #{NO_ACTION}            | ${T}              | CSDP            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{REMOVE_NODE}        | ACCU         | WilliamHill PTY LTD  | 3/240 CARRINGTON ROAD    | Leppington | FRGN       |                 | PricgSchme}' is expected                                                                         |

  Scenario Outline: PAC1 PAC3 PAC8 Account Creation message - Schema invalid - <Description>
    When I generate a message from template for "acct001" using datatable and publish on adapter "ISO"
      | BAH_From  | BAH_BizMsgIdr                               | MessageId                               | BAH_CreDt                 | SctiesAcct_OpngDt | Sup_AcctType   | Sup_Name   | Sup_AdrLine1   | Sup_TwnNm   | Sup_CtrySubDvsn | Sup_Ctry   | Sup_ResInd   | Sup_ComMtdCd   | SplmtryData   |
      | <ActorId> | <ActorId>${BAH_BizMsgIdr::format=\|Account} | <ActorId>${MessageId::format=\|Account} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}              | <Sup_AcctType> | <Sup_Name> | <Sup_AdrLine1> | <Sup_TwnNm> | #{ADD_NODE}NSW  | <Sup_Ctry> | <Sup_ResInd> | <Sup_ComMtdCd> | <SplmtryData> |
    Then verify NACK with number of messages "1" on outbound queue of "ASXML_OUT" and on poison queue of inbound adapter "ASXML" with message type "comm807"
      | Validate_BAH | Validate_Rltd_BAH         | BAH_To    | Nack_Rltd_RefId                             | RejectReasonCode | RejectReasonDescription   |
      | true         | true::IngressLink=acct001 | <ActorId> | <ActorId>${OriginalMsgId::format=\|Account} |             0099 | <RejectReasonDescription> |
    And Verify the "Account" report doesn't exist in ODS for the following attributes from the below table
      | ActorId   | AccountType    | ResidencyIndicator |
      | <ActorId> | <Sup_AcctType> | <Sup_ResInd>       |

    #Mandatory fields in Supplementary data block missing
    @REPORT_SPD-161_SPD-165_2
    Examples: 
      | Description                                                     | ActorId                        | SplmtryData    | Sup_AcctType   | Sup_Name           | Sup_AdrLine1                     | Sup_TwnNm         | Sup_Ctry      | Sup_ResInd      | Sup_ComMtdCd    | RejectReasonDescription                                                                           |
      | Supplementary Data - Account Type is blank                      | ${#FEATURE#Actor_CDRA.ActorId} | #{NO_ACTION}   |                | RICHARD PTY LTD    | #{ADD_NODE}3/240 CARRINGTON ROAD | #{ADD_NODE}COOGEE | #{ADD_NODE}AU | #{ADD_NODE}MIXD |                 | Value '' is not facet-valid with respect to enumeration '[SETT, DRCT, SPSD, ACCU]'                |
      | Payload without Supplementary Data - Account Type element       | ${#FEATURE#Actor_CDRA.ActorId} | #{NO_ACTION}   | #{REMOVE_NODE} | P&J PTY LTD        | #{ADD_NODE}3/240 DOUGLAS ROAD    | #{ADD_NODE}COOGEE | #{ADD_NODE}AU | #{ADD_NODE}DMST |                 | AcctTp}' is expected                                                                              |
      | Supplementary Data - Account Name is blank                      | ${#FEATURE#Actor_CDRA.ActorId} | #{NO_ACTION}   | DRCT           |                    | #{ADD_NODE}3/240 DUNNWAY ROAD    | #{ADD_NODE}COOGEE | #{ADD_NODE}AU | #{ADD_NODE}FRGN |                 | Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'Max350Text' |
      | Payload without Supplementary Data - Account Name element       | ${#FEATURE#Actor_CDRA.ActorId} | #{NO_ACTION}   | DRCT           | #{REMOVE_NODE}     | #{ADD_NODE}3/240 COORE ROAD      | #{ADD_NODE}COOGEE | #{ADD_NODE}AU | #{ADD_NODE}MIXD |                 | Nm}' is expected                                                                                  |
      | Supplementary Data - Address Line is blank                      | ${#FEATURE#Actor_CSPA.ActorId} | #{NO_ACTION}   | SPSD           | SCHNEIDER PTY LTD  | #{ADD_NODE}                      | #{ADD_NODE}COOGEE | #{ADD_NODE}AU | #{ADD_NODE}MIXD | #{ADD_NODE}POST | Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'Max70Text'  |
      | Payload without Supplementary Data - Address Line element       | ${#FEATURE#Actor_CSPA.ActorId} | #{NO_ACTION}   | SPSD           | RICHARDSON PTY LTD |                                  | #{ADD_NODE}COOGEE | #{ADD_NODE}AU | #{ADD_NODE}FRGN | #{ADD_NODE}POST | AdrLine}' is expected                                                                             |
      | Supplementary Data - Town Name is blank                         | ${#FEATURE#Actor_CETA.ActorId} | #{NO_ACTION}   | SETT           | ELDERS PTY LTD     | #{ADD_NODE}3/240 MONT ROAD       | #{ADD_NODE}       | #{ADD_NODE}AU | #{ADD_NODE}DMST |                 | Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'Max35Text'  |
      | Payload without Supplementary Data - Town Name element          | ${#FEATURE#Actor_CETA.ActorId} | #{NO_ACTION}   | SETT           | STW PTY LTD        | #{ADD_NODE}3/240 GEORGE ST       |                   | #{ADD_NODE}AU | #{ADD_NODE}FRGN |                 | TwnNm}' is expected                                                                               |
      | Supplementary Data - Country Code is blank                      | ${#FEATURE#Actor_CETA.ActorId} | #{NO_ACTION}   | ACCU           | BCG PTY LTD        | #{ADD_NODE}3/240 PITT ST         | #{ADD_NODE}Cooma  | #{ADD_NODE}   | #{ADD_NODE}DMST |                 | Value '' is not facet-valid with respect to pattern '[A-Z]{2,2}'                                  |
      | Payload without Supplementary Data - Country Code element       | ${#FEATURE#Actor_CETA.ActorId} | #{NO_ACTION}   | ACCU           | Bayer PTY LTD      | #{ADD_NODE}3/240 GWH             | #{ADD_NODE}Cooma  |               | #{ADD_NODE}FRGN |                 | Ctry}' is expected                                                                                |
      | Supplementary Data - Residency Indicator is blank               | ${#FEATURE#Actor_CDRA.ActorId} | #{NO_ACTION}   | DRCT           | Accord PTY LTD     | #{ADD_NODE}3/240 PYE ROAD        | #{ADD_NODE}Boral  | #{ADD_NODE}AU | #{ADD_NODE}     |                 | Value '' is not facet-valid with respect to enumeration '[DMST, FRGN, MIXD]'                      |
      | Payload without Supplementary Data -Residency Indicator element | ${#FEATURE#Actor_CDRA.ActorId} | #{NO_ACTION}   | DRCT           | NDM PTY LTD        | #{ADD_NODE}3/240 MARSDON ROAD    | #{ADD_NODE}Boral  | #{ADD_NODE}AU |                 |                 | ResInd}' is expected                                                                              |
      | Payload without Supplementary Data block                        | ${#FEATURE#Actor_CDRA.ActorId} | #{REMOVE_NODE} | #{NO_ACTION}   | #{NO_ACTION}       | #{NO_ACTION}                     | #{NO_ACTION}      | #{NO_ACTION}  | #{NO_ACTION}    |                 | SplmtryData}' is expected                                                                         |

  Scenario Outline: PAC1 PAC3 Account Creation message - <Description>
    When I generate a message from template for "acct001" using datatable and publish on adapter "ISO"
      | BAH_From  | BAH_BizMsgIdr                               | MessageId   | BAH_CreDt                 | SctiesAcct_Id   | SctiesAcct_OpngDt   | SctiesAcct_Type   | SctiesAcct_HoldInd   | SctiesAcct_NegPos   | SctiesAcct_EndInvstrFlg   | SctiesAcct_PricgSchme   | Sup_AcctType   | Sup_Name   | Sup_AdrLine1              | Sup_TwnNm              | Sup_CtrySubDvsn | Sup_Ctry      | Sup_ResInd              | Sup_ComMtdCd   |
      | <ActorId> | <ActorId>${BAH_BizMsgIdr::format=\|Account} | <MessageId> | ${T::DateFormatter=ZuluWithMilliSec} | <SctiesAcct_Id> | <SctiesAcct_OpngDt> | <SctiesAcct_Type> | <SctiesAcct_HoldInd> | <SctiesAcct_NegPos> | <SctiesAcct_EndInvstrFlg> | <SctiesAcct_PricgSchme> | <Sup_AcctType> | <Sup_Name> | #{ADD_NODE}<Sup_AdrLine1> | #{ADD_NODE}<Sup_TwnNm> | #{ADD_NODE}NSW  | #{ADD_NODE}AU | #{ADD_NODE}<Sup_ResInd> | <Sup_ComMtdCd> |
    Then verify NACK with number of messages "1" on outbound queue of "ASXML_OUT" and on poison queue of inbound adapter "ASXML" with message type "comm807"
      | Validate_BAH | Validate_Rltd_BAH         | BAH_To    | Nack_Rltd_RefId                             | RejectReasonCode | RejectReasonDescription   |
      | true         | true::IngressLink=acct001 | <ActorId> | <ActorId>${OriginalMsgId::format=\|Account} |             0099 | <RejectReasonDescription> |

    #Invalid data format in Account Creation Request block
    @REPORT_SPD-161_SPD-165_3
    Examples: 
      | Description                                               | ActorId                        | MessageId                               | SctiesAcct_Id | SctiesAcct_OpngDt                    | SctiesAcct_Type | SctiesAcct_HoldInd | SctiesAcct_NegPos | SctiesAcct_EndInvstrFlg | SctiesAcct_PricgSchme | Sup_AcctType | Sup_Name             | Sup_AdrLine1             | Sup_TwnNm | Sup_ResInd | Sup_ComMtdCd    | RejectReasonDescription                                                |
      | Payload with invalid Account - Id - as32423424            | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | as32423424    | ${T}                                 | #{NO_ACTION}    | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SPSD         | Schneider PTY LTD    | 101 HARRINGTON ROAD      | Boral     | DMST       | #{ADD_NODE}POST | Value 'as32423424' is not facet-valid with respect to pattern 'NONREF' |
      | Payload with invalid Account - Opening Date format (Zulu) | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}  | ${T::DateFormatter=ZuluWithMilliSec} | #{NO_ACTION}    | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SPSD         | Schneider PTY LTD    | 101 HARRINGTON ROAD      | Boral     | DMST       | #{ADD_NODE}POST | is not a valid value for 'date'                                        |
      | Payload with invalid Account - Type - CXXR                | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}  | ${T}                                 | CXXR            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SPSD         | Schneider PTY LTD    | 101 HARRINGTON ROAD      | Boral     | DMST       | #{ADD_NODE}POST | Value 'CXXR' is not facet-valid with respect to enumeration '[CSDP]'   |
      | Payload with CSD Omnibus Account type                     | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}  | ${T}                                 | CSDO            | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SPSD         | Schneider PTY LTD    | 101 HARRINGTON ROAD      | Boral     | DMST       | #{ADD_NODE}POST | Value 'CSDO' is not facet-valid with respect to enumeration '[CSDP]'   |
      | Payload with invalid Hold Indicator - Y                   | ${#FEATURE#Actor_CETA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}  | ${T}                                 | #{NO_ACTION}    | Y                  | #{NO_ACTION}      | #{NO_ACTION}            | #{NO_ACTION}          | SETT         | Energy Australia LTD | 56 GREAT WESTREN HIGHWAY | Cooma     | FRGN       |                 | Value 'Y' is not facet-valid with respect to enumeration '[false]'     |
      | Payload with invalid Negative Position - N                | ${#FEATURE#Actor_CDRA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}  | ${T}                                 | #{NO_ACTION}    | #{NO_ACTION}       | N                 | #{NO_ACTION}            | #{NO_ACTION}          | DRCT         | RJ  PTY LTD          | 3/240 CARRINGTON ROAD    | Penrith   | FRGN       |                 | Value 'N' is not facet-valid with respect to enumeration '[false]'     |
      | Payload with invalid End Investor Flag - ST               | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}  | ${T}                                 | #{NO_ACTION}    | #{NO_ACTION}       | #{NO_ACTION}      | ST                      | #{NO_ACTION}          | SPSD         | RICHARD PTY LTD      | 3/240 CARRINGTON ROAD    | Richmond  | DMST       | #{ADD_NODE}POST | Value 'ST' is not facet-valid with respect to enumeration '[NORE]'     |
      | Payload with invalid Pricing Scheme - T                   | ${#FEATURE#Actor_CSPA.ActorId} | <ActorId>${MessageId::format=\|Account} | #{NO_ACTION}  | ${T}                                 | #{NO_ACTION}    | #{NO_ACTION}       | #{NO_ACTION}      | #{NO_ACTION}            | T                     | SPSD         | RICHARDSON PTY LTD   | 3/240 CARRINGTON ROAD    | Richmond  | FRGN       | #{ADD_NODE}POST | Value 'T' is not facet-valid with respect to enumeration '[NORE]'      |

  Scenario Outline: PAC1 PAC3 Account Creation message - Payload with Supplementary Data - <Description>
    When I generate a message from template for "acct001" using datatable and publish on adapter "ISO"
      | BAH_From  | BAH_BizMsgIdr                               | MessageId                               | BAH_CreDt                 | SctiesAcct_OpngDt | Sup_AcctType   | Sup_Name   | Sup_AdrLine1              | Sup_PstCd              | Sup_TwnNm              | Sup_CtrySubDvsn              | Sup_Ctry              | Sup_ResInd   | Sup_ComMtdCd   |
      | <ActorId> | <ActorId>${BAH_BizMsgIdr::format=\|Account} | <ActorId>${MessageId::format=\|Account} | ${T::DateFormatter=ZuluWithMilliSec} | ${T}              | <Sup_AcctType> | <Sup_Name> | #{ADD_NODE}<Sup_AdrLine1> | #{ADD_NODE}<Sup_PstCd> | #{ADD_NODE}<Sup_TwnNm> | #{ADD_NODE}<Sup_CtrySubDvsn> | #{ADD_NODE}<Sup_Ctry> | <Sup_ResInd> | <Sup_ComMtdCd> |
    Then verify NACK with number of messages "1" on outbound queue of "ASXML_OUT" and on poison queue of inbound adapter "ASXML" with message type "comm807"
      | Validate_BAH | Validate_Rltd_BAH         | BAH_To    | Nack_Rltd_RefId                             | RejectReasonCode | RejectReasonDescription   |
      | true         | true::IngressLink=acct001 | <ActorId> | <ActorId>${OriginalMsgId::format=\|Account} |             0099 | <RejectReasonDescription> |
    And Verify the "Account" report doesn't exist in ODS for the following attributes from the below table
      | ActorId   | AccountType    | ResidencyIndicator |
      | <ActorId> | <Sup_AcctType> | <Sup_ResInd>       |

    #Invalid data formats in Supplementary data block
    @REPORT_SPD-161_SPD-165_4
    Examples: 
      | Description                                                  | ActorId                        | Sup_AcctType                 | Sup_Name          | Sup_AdrLine1          | Sup_PstCd | Sup_TwnNm        | Sup_CtrySubDvsn | Sup_Ctry | Sup_ResInd       | Sup_ComMtdCd    | RejectReasonDescription                                                                          |
      | Account Type in lower case (drct)                            | ${#FEATURE#Actor_CDRA.ActorId} | drct                         | RICHARD PTY LTD   | 45, Carrington Road   |      4000 | Amsterdam        | SQD             | NL       | #{ADD_NODE}MIXD  |                 | Value 'drct' is not facet-valid with respect to enumeration '[SETT, DRCT, SPSD, ACCU]'           |
      | Account Type with spaces ( ACCU )                            | ${#FEATURE#Actor_CETA.ActorId} | #{ADD_SPACE}ACCU#{ADD_SPACE} | RICHARD PTY LTD   | 55, George Avenue     |      4908 | Brunswick        | TAS             | AU       | #{ADD_NODE}DMST  |                 | is not facet-valid with respect to enumeration '[SETT, DRCT, SPSD, ACCU]'                        |
      | Invalid Account Type                                         | ${#FEATURE#Actor_CSPA.ActorId} | SWERy                        | P&J PTY LTD       | 45, Pitt St           |      4908 | Paris            | ASE             | FR       | #{ADD_NODE}FRGN  | #{ADD_NODE}POST | Value 'SWERy' is not facet-valid with respect to enumeration '[SETT, DRCT, SPSD, ACCU]'          |
      | Create sponsored account with blank communication preference | ${#FEATURE#Actor_CSPA.ActorId} | SPSD                         | RICHARD PTY LTD   | 3/240 CARRINGTON ROAD |      2179 | COOGEE           | NSW             | AU       | #{ADD_NODE}MIXD  | #{ADD_NODE}     | Value '' is not facet-valid with respect to enumeration '[EMAL, POST]'                           |
      | Residency Indicator in lower case (dmst)                     | ${#FEATURE#Actor_CDRA.ActorId} | DRCT                         | RICHARD PTY LTD   | 7, Darcy Road         |      7899 | Leura            | TAS             | AU       | #{ADD_NODE}dmst  |                 | Value 'dmst' is not facet-valid with respect to enumeration '[DMST, FRGN, MIXD]'                 |
      | Residency Indicator with spaces ( MIXD)                      | ${#FEATURE#Actor_CSPA.ActorId} | SPSD                         | RICHARD PTY LTD   | 44, Philip Avenue     |      7899 | Tampines         | SG              | SG       | #{ADD_NODE} MIXD | #{ADD_NODE}POST | Value ' MIXD' is not facet-valid with respect to enumeration '[DMST, FRGN, MIXD]'                |
      | Invalid Residency Indicator - FRG                            | ${#FEATURE#Actor_CETA.ActorId} | SETT                         | P&J PTY LTD       | 100, Argyle Street    |      6002 | Kiama            | VIC             | AU       | #{ADD_NODE}FRG   |                 | Value 'FRG' is not facet-valid with respect to enumeration '[DMST, FRGN, MIXD]'                  |
      | blank country sub-division                                   | ${#FEATURE#Actor_CDRA.ActorId} | DRCT                         | SCHNEIDER PTY LTD | 3 CARRINGTON ROAD     |      2056 | Pymble           |                 | AU       | #{ADD_NODE}MIXD  |                 | Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'Max35Text' |
      | Country Code in lower case (au)                              | ${#FEATURE#Actor_CETA.ActorId} | SETT                         | RICHARD PTY LTD   | 45 Dunmore St         |      2098 | COOGEE           | VIC             | au       | #{ADD_NODE}DMST  |                 | Value 'au' is not facet-valid with respect to pattern '[A-Z]{2,2}'                               |
      | Invalid Country Code (USA)                                   | ${#FEATURE#Actor_CDRA.ActorId} | DRCT                         | Ford Group LTD    | 22 Marcel Cr          |     60090 | Farmington Hills | Detroit         | USA      | #{ADD_NODE}FRGN  |                 | Value 'USA' is not facet-valid with respect to pattern '[A-Z]{2,2}'                              |
      | blank postal code                                            | ${#FEATURE#Actor_CETA.ActorId} | ACCU                         | Bayer Pty Ltd     | 45 CARRINGTON ROAD    |           | Botany           | TAS             | AU       | #{ADD_NODE}DMST  |                 | Value '' with length = '0' is not facet-valid with respect to minLength '1' for type 'Max16Text' |
